      - name: Terraform Init (reconfigure backend)
        run: terraform init -reconfigure

      - name: Show current Terraform state
        run: terraform state list || true

      - name: Import DynamoDB table if missing
        run: |
          terraform state show aws_dynamodb_table.outage_logs > /dev/null 2>&1 || terraform import aws_dynamodb_table.outage_logs OutageLogs

      - name: Import IAM role if missing
        run: |
          terraform state show aws_iam_role.lambda_role > /dev/null 2>&1 || terraform import aws_iam_role.lambda_role outage-api-lambda-role

      - name: Import Lambda function if missing
        run: |
          terraform state show aws_lambda_function.outage_api > /dev/null 2>&1 || terraform import aws_lambda_function.outage_api OutageLogAPI

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false